# Generated by Django 6.1.1 on 2026-09-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
