# Generated by Django 6.1.1 on 2026-09-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Account Credit'), ('withdraw', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
