# Generated by Django 6.1.1 on 2026-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('In Progress', 'In Progress'), ('Awaiting Customer', 'Awaiting Customer'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Received', max_length=30),
        ),
    ]
